[webservers]
44.215.176.176
100.28.120.121


[webservers:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/ec2-user/1_percent_keypair517.pem 


##//  THIS FILE IS ONLY TO SHOW HOW THE YAML FILE IS CREATED FOR ANSIBLE.THIS FILE REAL LOCATION IS IN THE ANSIBLE CONTROL SERVER WITH INVENTORY.INI
